// AIVPC V5.4 Drug Seed Data - Part 1 (first 22 drugs)
export interface DrugSeedRecord {
  trade_name: string;
  generic_name: string;
  arabic_name: string;
  form: "Powder" | "Solution";
  container: "Vial" | "Ampoule";
  amount_mg: number;
  amount_volume_ml: number | null;
  concentration_mg_ml: number | null;
  reconstitution_volume_ml: number | null;
  reconstitution_concentration_mg_ml: number | null;
  reconstitution_diluent_ns: number;
  reconstitution_diluent_d5w: number;
  reconstitution_diluent_swi: number;
  reconstitution_stability_room_hours: number | null;
  reconstitution_stability_refrigeration_days: number | null;
  initial_dilution_volume_ml: number | null;
  initial_dilution_concentration_mg_ml: number | null;
  fd_each_ml_up_to: number | null;
  fd_concentration_mg_ml: number | null;
  fdfr_each_ml_up_to: number | null;
  fdfr_concentration_mg_ml: number | null;
  fd_diluent_ns: number;
  fd_diluent_d5w: number;
  fd_stability_room_hours: number | null;
  fd_stability_refrigeration_days: number | null;
  infusion_time_min: number;
  is_photosensitive: number;
  is_biohazard: number;
  min_dose_mg_kg_dose: number;
  max_dose_mg_kg_dose: number;
  max_dose_mg_dose: number;
  max_dose_mg_day: number;
  obese_patient_dosage_adjustment: string;
  instructions_text: string;
  target_volume_ml: number;
}

export const drugSeedData: DrugSeedRecord[] = [
  {
    trade_name: "Ambisome",
    generic_name: "Amphotericin B, Liposomal",
    arabic_name: "أمبيزوم",
    form: "Powder",
    container: "Vial",
    amount_mg: 50,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 12,
    reconstitution_concentration_mg_ml: 4,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 7,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 8,
    fd_concentration_mg_ml: 0.5,
    fdfr_each_ml_up_to: 2,
    fdfr_concentration_mg_ml: 2,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 48,
    fd_stability_refrigeration_days: 7,
    infusion_time_min: 120,
    is_photosensitive: 1,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 2.5,
    max_dose_mg_kg_dose: 12,
    max_dose_mg_dose: 200,
    max_dose_mg_day: 800,
    obese_patient_dosage_adjustment: "TBW",
    instructions_text:
      "(Amphotericin B, Liposomal) 50mg Powder Vial Should be reconstituted with 12ml of SWI to produce concentration of 4mg/ml and will be stable for 24 hours in Room Temp and for 7 days in Refrigeration. Withdraw the Calculated mls and Further dilute with D5W each ml up to 8 ml. The Final concentration will be 0.5 mg/ml that will be stable for 48 hours in Room Temp. and 7 days in Refrigeration",
    target_volume_ml: 12.5,
  },
  {
    trade_name: "Amikacin",
    generic_name: "Amikacin",
    arabic_name: "أميكين",
    form: "Solution",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: 2,
    concentration_mg_ml: 250,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: 10,
    initial_dilution_concentration_mg_ml: 50,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 5,
    fdfr_each_ml_up_to: 5,
    fdfr_concentration_mg_ml: 10,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 14,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 5,
    max_dose_mg_kg_dose: 30,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 1500,
    obese_patient_dosage_adjustment: "0.7 x TBW",
    instructions_text:
      "(Amikacin) 500mg per 2ml Solution Vial with concentration of 250 mg/ml and should be initially diluted with 10ml of NS or D5W to create concentration of 50 mg/ml and must be used immediately. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 5 mg/ml that will be stable for 24 hours in Room Temp. and 14 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Cefobid",
    generic_name: "Cefoperazone",
    arabic_name: "سيفوبيد",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 5,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 5,
    fd_concentration_mg_ml: 10,
    fdfr_each_ml_up_to: 2,
    fdfr_concentration_mg_ml: 25,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 5,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 50,
    max_dose_mg_kg_dose: 200,
    max_dose_mg_dose: 4000,
    max_dose_mg_day: 12000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Cefoperazone) 500mg Powder Vial Should be reconstituted with 10ml of NS, D5W or SWI to produce concentration of 50mg/ml and will be stable for 24 hours in Room Temp and for 5 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 5 ml. The Final concentration will be 10 mg/ml that will be stable for 24 hours in Room Temp. and 5 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Cefotax 1000",
    generic_name: "Cefotaxime",
    arabic_name: "سيفوتاكس",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 7,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 40,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 5,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 300,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 12000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Cefotaxime) 1000mg Powder Vial Should be reconstituted with 10ml of SWI to produce concentration of 100mg/ml and will be stable for 24 hours in Room Temp and for 7 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 40 mg/ml that will be stable for 24 hours in Room Temp. and 5 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Cefotax 500",
    generic_name: "Cefotaxime",
    arabic_name: "سيفوتاكس",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 7,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 1.25,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 1.25,
    fdfr_concentration_mg_ml: 40,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 5,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 300,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 12000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Cefotaxime) 500mg Powder Vial Should be reconstituted with 10ml of SWI to produce concentration of 50mg/ml and will be stable for 24 hours in Room Temp and for 7 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 1.25 ml. The Final concentration will be 40 mg/ml that will be stable for 24 hours in Room Temp. and 5 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Ciprofloxacin 200/100",
    generic_name: "Ciprofloxacin",
    arabic_name: "سيبرو",
    form: "Solution",
    container: "Vial",
    amount_mg: 200,
    amount_volume_ml: 100,
    concentration_mg_ml: 2,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 14,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 6,
    max_dose_mg_kg_dose: 20,
    max_dose_mg_dose: 400,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "EBW + 0.45 (TBW-EBW)",
    instructions_text:
      "(Ciprofloxacin) 200mg per 100ml Solution Vial with concentration of 2 mg/ml and will be stable for 24 hours in Room Temp and for 14 days in Refrigeration. Withdraw the Calculated mls",
    target_volume_ml: 100,
  },
  {
    trade_name: "Ciprofloxacin 200/20",
    generic_name: "Ciprofloxacin",
    arabic_name: "سيبرو",
    form: "Solution",
    container: "Vial",
    amount_mg: 200,
    amount_volume_ml: 20,
    concentration_mg_ml: 10,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 5,
    fd_concentration_mg_ml: 2,
    fdfr_each_ml_up_to: 5,
    fdfr_concentration_mg_ml: 2,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 14,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 6,
    max_dose_mg_kg_dose: 20,
    max_dose_mg_dose: 400,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "EBW + 0.45 (TBW-EBW)",
    instructions_text:
      "(Ciprofloxacin) 200mg per 20ml Solution Vial with concentration of 10 mg/ml and must be used immediately. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 5 ml. The Final concentration will be 2 mg/ml that will be stable for 24 hours in Room Temp. and 14 days in Refrigeration",
    target_volume_ml: 20,
  },
  {
    trade_name: "Colistin 1M",
    generic_name: "Polymyxin E",
    arabic_name: "كوليستين",
    form: "Powder",
    container: "Vial",
    amount_mg: 33.33,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 3,
    reconstitution_concentration_mg_ml: 11.1,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 1.11,
    fdfr_each_ml_up_to: 3,
    fdfr_concentration_mg_ml: 3.7,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 0.8,
    max_dose_mg_kg_dose: 5,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "IBW",
    instructions_text:
      "(Polymyxin E) 33.33mg Powder Vial Should be reconstituted with 3ml of NS, D5W or SWI to produce concentration of 11.11mg/ml and will be stable for 24 hours in Room Temp and for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 1.1 mg/ml that will be stable for 24 hours in Room Temp. and 24 hours in Refrigeration",
    target_volume_ml: 3,
  },
  {
    trade_name: "Colistin 2M",
    generic_name: "Polymyxin E",
    arabic_name: "كوليستين",
    form: "Powder",
    container: "Vial",
    amount_mg: 66.66,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 6,
    reconstitution_concentration_mg_ml: 11.1,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 1.11,
    fdfr_each_ml_up_to: 3,
    fdfr_concentration_mg_ml: 3.7,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 0.8,
    max_dose_mg_kg_dose: 5,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "IBW",
    instructions_text:
      "(Polymyxin E) 66.66mg Powder Vial Should be reconstituted with 6ml of NS, D5W or SWI to produce concentration of 11.11mg/ml and will be stable for 24 hours in Room Temp and for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 1.1 mg/ml that will be stable for 24 hours in Room Temp. and 24 hours in Refrigeration",
    target_volume_ml: 6,
  },
  {
    trade_name: "Dalacin",
    generic_name: "Clindamycin",
    arabic_name: "دلاسين",
    form: "Solution",
    container: "Ampoule",
    amount_mg: 600,
    amount_volume_ml: 4,
    concentration_mg_ml: 150,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 48,
    reconstitution_stability_refrigeration_days: 14,
    initial_dilution_volume_ml: 40,
    initial_dilution_concentration_mg_ml: 15,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 5,
    max_dose_mg_kg_dose: 40,
    max_dose_mg_dose: 900,
    max_dose_mg_day: 2700,
    obese_patient_dosage_adjustment: "TBW",
    instructions_text:
      "(Clindamycin) 600mg per 4ml Solution Ampoule with concentration of 150 mg/ml and should be initially diluted with 40ml of NS or D5W to create concentration of 15 mg/ml and will be stable for 48 hours in Room Temp and for 14 days in Refrigeration. Withdraw the Calculated mls",
    target_volume_ml: 40,
  },
  {
    trade_name: "Diflucan",
    generic_name: "Fluconazole",
    arabic_name: "ديفلوكان",
    form: "Solution",
    container: "Vial",
    amount_mg: 200,
    amount_volume_ml: 100,
    concentration_mg_ml: 2,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 120,
    is_photosensitive: 0,
    is_biohazard: 1,
    min_dose_mg_kg_dose: 3,
    max_dose_mg_kg_dose: 25,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 800,
    obese_patient_dosage_adjustment: "TBW (max 1,200 mg/day)",
    instructions_text:
      "(Fluconazole) 200mg per 100ml Solution Vial with concentration of 2 mg/ml and must be used immediately. Withdraw the Calculated mls",
    target_volume_ml: 100,
  },
  {
    trade_name: "Flagyl",
    generic_name: "Metronidazole",
    arabic_name: "فلاجيل",
    form: "Solution",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: 100,
    concentration_mg_ml: 5,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 7.5,
    max_dose_mg_kg_dose: 30,
    max_dose_mg_dose: 1000,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "EBW or 1500mg max dose",
    instructions_text:
      "(Metronidazole) 500mg per 100ml Solution Vial with concentration of 5 mg/ml and must be used immediately. Withdraw the Calculated mls",
    target_volume_ml: 100,
  },
  {
    trade_name: "Fortum 1000",
    generic_name: "Ceftazidime",
    arabic_name: "فورتم",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 12,
    reconstitution_stability_refrigeration_days: 3,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 2,
    fdfr_concentration_mg_ml: 50,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 12,
    fd_stability_refrigeration_days: 3,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 400,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 12000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Ceftazidime) 1000mg Powder Vial Should be reconstituted with 10ml of NS or D5W to produce concentration of 100mg/ml and will be stable for 12 hours in Room Temp and for 3 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 40 mg/ml that will be stable for 12 hours in Room Temp. and 3 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Fortum 500",
    generic_name: "Ceftazidime",
    arabic_name: "فورتم",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 5,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 12,
    reconstitution_stability_refrigeration_days: 3,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 2,
    fdfr_concentration_mg_ml: 50,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 12,
    fd_stability_refrigeration_days: 3,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 400,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 12000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Ceftazidime) 500mg Powder Vial Should be reconstituted with 5ml of NS or D5W to produce concentration of 100mg/ml and will be stable for 12 hours in Room Temp and for 3 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 40 mg/ml that will be stable for 12 hours in Room Temp. and 3 days in Refrigeration",
    target_volume_ml: 5,
  },
  {
    trade_name: "Fungizone",
    generic_name: "Amphotericin B, Conventional",
    arabic_name: "فنجيزون",
    form: "Powder",
    container: "Vial",
    amount_mg: 50,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 5,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 7,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 50,
    fd_concentration_mg_ml: 0.1,
    fdfr_each_ml_up_to: 20,
    fdfr_concentration_mg_ml: 0.25,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 14,
    infusion_time_min: 180,
    is_photosensitive: 1,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 0.25,
    max_dose_mg_kg_dose: 1.5,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 800,
    obese_patient_dosage_adjustment: "TBW",
    instructions_text:
      "(Amphotericin B, Conventional) 50mg Powder Vial Should be reconstituted with 10ml of D5W to produce concentration of 5mg/ml and will be stable for 24 hours in Room Temp and for 7 days in Refrigeration. Withdraw the Calculated mls and Further dilute with D5W each ml up to 50 ml. The Final concentration will be 0.1 mg/ml that will be stable for 24 hours in Room Temp. and 14 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Ganciclovir",
    generic_name: "Ganciclovir",
    arabic_name: "جانسيكلوفير",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 12,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 6.25,
    fd_concentration_mg_ml: 8,
    fdfr_each_ml_up_to: 5,
    fdfr_concentration_mg_ml: 10,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 1,
    min_dose_mg_kg_dose: 5,
    max_dose_mg_kg_dose: 7.5,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "EBW",
    instructions_text:
      "(Ganciclovir) 500mg Powder Vial Should be reconstituted with 10ml of SWI to produce concentration of 50mg/ml and will be stable for 12 hours in Room Temp. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 6.25 ml. The Final concentration will be 8 mg/ml that will be stable for 24 hours in Room Temp.",
    target_volume_ml: 10,
  },
  {
    trade_name: "Gentamicin 20/2",
    generic_name: "Gentamicin",
    arabic_name: "جنتاميسين",
    form: "Solution",
    container: "Ampoule",
    amount_mg: 20,
    amount_volume_ml: 2,
    concentration_mg_ml: 10,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 4,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 2,
    max_dose_mg_kg_dose: 7.5,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "0.7 x TBW",
    instructions_text:
      "(Gentamicin) 20mg per 2ml Solution Ampoule with concentration of 10 mg/ml and will be stable for 24 hours in Room Temp and for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 4 mg/ml that will be stable for 24 hours in Room Temp. and 24 hours in Refrigeration",
    target_volume_ml: 2,
  },
  {
    trade_name: "Gentamicin 80/2",
    generic_name: "Gentamicin",
    arabic_name: "جنتاميسين",
    form: "Solution",
    container: "Ampoule",
    amount_mg: 80,
    amount_volume_ml: 2,
    concentration_mg_ml: 40,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: 8,
    initial_dilution_concentration_mg_ml: 10,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 4,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 2,
    max_dose_mg_kg_dose: 7.5,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "0.7 x TBW",
    instructions_text:
      "(Gentamicin) 80mg per 2ml Solution Ampoule with concentration of 40 mg/ml and should be initially diluted with 8ml of NS or D5W to create concentration of 10 mg/ml and must be used immediately. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 4 mg/ml that will be stable for 24 hours in Room Temp. and 24 hours in Refrigeration",
    target_volume_ml: 8,
  },
  {
    trade_name: "Invanz",
    generic_name: "Ertapenem",
    arabic_name: "إنفانز",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 4,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 5,
    fd_concentration_mg_ml: 20,
    fdfr_each_ml_up_to: 5,
    fdfr_concentration_mg_ml: 20,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: 4,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 15,
    max_dose_mg_kg_dose: 15,
    max_dose_mg_dose: 500,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Ertapenem) 1000mg Powder Vial Should be reconstituted with 10ml of NS to produce concentration of 100mg/ml and will be stable for 4 hours in Room Temp and for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS each ml up to 5 ml. The Final concentration will be 20 mg/ml that will be stable for 4 hours in Room Temp. and 24 hours in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Linezolid",
    generic_name: "Linezolid",
    arabic_name: "لينيزوليد",
    form: "Solution",
    container: "Vial",
    amount_mg: 200,
    amount_volume_ml: 100,
    concentration_mg_ml: 2,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 10,
    max_dose_mg_kg_dose: 15,
    max_dose_mg_dose: 600,
    max_dose_mg_day: 1200,
    obese_patient_dosage_adjustment: "EBW",
    instructions_text:
      "(Linezolid) 200mg per 100ml Solution Vial with concentration of 2 mg/ml and must be used immediately. Withdraw the Calculated mls",
    target_volume_ml: 100,
  },
  {
    trade_name: "Maxipime 1000",
    generic_name: "Cefepime",
    arabic_name: "ماكسيبيم",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 9,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 7,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 40,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 7,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 30,
    max_dose_mg_kg_dose: 100,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 8000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Cefepime) 1000mg Powder Vial Should be reconstituted with 9ml of NS or D5W to produce concentration of 100mg/ml and will be stable for 24 hours in Room Temp and for 7 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 40 mg/ml that will be stable for 24 hours in Room Temp. and 7 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Maxipime 500",
    generic_name: "Cefepime",
    arabic_name: "ماكسيبيم",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 4.6,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 7,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 40,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 7,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 30,
    max_dose_mg_kg_dose: 100,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 8000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Cefepime) 500mg Powder Vial Should be reconstituted with 4.6ml of NS or D5W to produce concentration of 100mg/ml and will be stable for 24 hours in Room Temp and for 7 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 40 mg/ml that will be stable for 24 hours in Room Temp. and 7 days in Refrigeration",
    target_volume_ml: 5,
  },
  {
    trade_name: "Meropenem 1000",
    generic_name: "Meropenem",
    arabic_name: "ميرونام",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 19.5,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 5,
    fd_concentration_mg_ml: 10,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 20,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: 3,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 20,
    max_dose_mg_kg_dose: 40,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Meropenem) 1000mg Powder Vial Should be reconstituted with 19.5ml of NS to produce concentration of 50mg/ml and must be used immediately. Withdraw the Calculated mls and Further dilute with NS each ml up to 5 ml. The Final concentration will be 10 mg/ml that will be stable for 3 hours in Room Temp. and 24 hours in Refrigeration",
    target_volume_ml: 20,
  },
  {
    trade_name: "Meropenem 500",
    generic_name: "Meropenem",
    arabic_name: "ميرونام",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 9.75,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 5,
    fd_concentration_mg_ml: 10,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 20,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: 3,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 20,
    max_dose_mg_kg_dose: 40,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Meropenem) 500mg Powder Vial Should be reconstituted with 9.75ml of NS to produce concentration of 50mg/ml and must be used immediately. Withdraw the Calculated mls and Further dilute with NS each ml up to 5 ml. The Final concentration will be 10 mg/ml that will be stable for 3 hours in Room Temp. and 24 hours in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Mycamine",
    generic_name: "Micafungin",
    arabic_name: "ميكامين",
    form: "Powder",
    container: "Vial",
    amount_mg: 50,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 5,
    reconstitution_concentration_mg_ml: 10,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 8,
    fd_concentration_mg_ml: 1.25,
    fdfr_each_ml_up_to: 6.6,
    fdfr_concentration_mg_ml: 1.52,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 1,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 1,
    max_dose_mg_kg_dose: 4,
    max_dose_mg_dose: 225,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "TBW (max 300 mg/day)",
    instructions_text:
      "(Micafungin) 50mg Powder Vial Should be reconstituted with 5ml of NS or D5W to produce concentration of 10mg/ml and will be stable for 24 hours in Room Temp. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 8 ml. The Final concentration will be 1.3 mg/ml that will be stable for 24 hours in Room Temp.",
    target_volume_ml: 5,
  },
  {
    trade_name: "Primafoxin",
    generic_name: "Cefoxitin",
    arabic_name: "بريمافوكسين",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 9.5,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 6,
    reconstitution_stability_refrigeration_days: 7,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 5,
    fd_concentration_mg_ml: 20,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 40,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 18,
    fd_stability_refrigeration_days: 2,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 30,
    max_dose_mg_kg_dose: 160,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Cefoxitin) 1000mg Powder Vial Should be reconstituted with 9.5ml of SWI to produce concentration of 100mg/ml and will be stable for 6 hours in Room Temp and for 7 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 5 ml. The Final concentration will be 20 mg/ml that will be stable for 18 hours in Room Temp. and 48 hours in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Rocephin 1000",
    generic_name: "Ceftriaxone",
    arabic_name: "روسفين",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 9.6,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 48,
    reconstitution_stability_refrigeration_days: 10,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 40,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 48,
    fd_stability_refrigeration_days: 10,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 300,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 4000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Ceftriaxone) 1000mg Powder Vial Should be reconstituted with 9.6ml of NS or D5W to produce concentration of 100mg/ml and will be stable for 48 hours in Room Temp and for 10 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 40 mg/ml that will be stable for 48 hours in Room Temp. and 10 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Rocephin 500",
    generic_name: "Ceftriaxone",
    arabic_name: "روسفين",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 4.8,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 48,
    reconstitution_stability_refrigeration_days: 10,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2.5,
    fd_concentration_mg_ml: 40,
    fdfr_each_ml_up_to: 2.5,
    fdfr_concentration_mg_ml: 40,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 48,
    fd_stability_refrigeration_days: 10,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 300,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 4000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Ceftriaxone) 500mg Powder Vial Should be reconstituted with 4.8ml of NS or D5W to produce concentration of 100mg/ml and will be stable for 48 hours in Room Temp and for 10 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2.5 ml. The Final concentration will be 40 mg/ml that will be stable for 48 hours in Room Temp. and 10 days in Refrigeration",
    target_volume_ml: 5,
  },
  {
    trade_name: "Targocid 200",
    generic_name: "Teicoplanin",
    arabic_name: "تارجوسيد",
    form: "Powder",
    container: "Vial",
    amount_mg: 200,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 3,
    reconstitution_concentration_mg_ml: 66.7,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 6.67,
    fdfr_each_ml_up_to: 1.5,
    fdfr_concentration_mg_ml: 44.44,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 6,
    max_dose_mg_kg_dose: 16,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "",
    instructions_text:
      "(Teicoplanin) 200mg Powder Vial Should be reconstituted with 3ml of SWI to produce concentration of 66.67mg/ml and will be stable for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 6.7 mg/ml that will be stable for 24 hours in Refrigeration",
    target_volume_ml: 3,
  },
  {
    trade_name: "Targocid 400",
    generic_name: "Teicoplanin",
    arabic_name: "تارجوسيد",
    form: "Powder",
    container: "Vial",
    amount_mg: 400,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 3,
    reconstitution_concentration_mg_ml: 133.3,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 20,
    fd_concentration_mg_ml: 6.67,
    fdfr_each_ml_up_to: 3,
    fdfr_concentration_mg_ml: 44.44,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 6,
    max_dose_mg_kg_dose: 16,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "",
    instructions_text:
      "(Teicoplanin) 400mg Powder Vial Should be reconstituted with 3ml of SWI to produce concentration of 133.33mg/ml and will be stable for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 20 ml. The Final concentration will be 6.7 mg/ml that will be stable for 24 hours in Refrigeration",
    target_volume_ml: 3,
  },
  {
    trade_name: "Tavanic",
    generic_name: "Levofloxacin",
    arabic_name: "تافانيك",
    form: "Solution",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: 100,
    concentration_mg_ml: 5,
    reconstitution_volume_ml: null,
    reconstitution_concentration_mg_ml: null,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 48,
    reconstitution_stability_refrigeration_days: 14,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 7.5,
    max_dose_mg_kg_dose: 20,
    max_dose_mg_dose: 750,
    max_dose_mg_day: 750,
    obese_patient_dosage_adjustment: "EBW + 0.45 (TBW-EBW)",
    instructions_text:
      "(Levofloxacin) 500mg per 100ml Solution Vial with concentration of 5 mg/ml and will be stable for 48 hours in Room Temp and for 14 days in Refrigeration. Withdraw the Calculated mls",
    target_volume_ml: 100,
  },
  {
    trade_name: "Tazocin",
    generic_name: "Piperacillin/Tazobactam",
    arabic_name: "تازوسين",
    form: "Powder",
    container: "Vial",
    amount_mg: 4000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 20,
    reconstitution_concentration_mg_ml: 174,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 2,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 4.5,
    fd_concentration_mg_ml: 38.67,
    fdfr_each_ml_up_to: 2.25,
    fdfr_concentration_mg_ml: 77.33,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 2,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 60,
    max_dose_mg_kg_dose: 100,
    max_dose_mg_dose: 4000,
    max_dose_mg_day: 24000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Piperacillin/Tazobactam) 4000mg Powder Vial Should be reconstituted with 20ml of NS or D5W to produce concentration of 174mg/ml and will be stable for 24 hours in Room Temp and for 48 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 4.5 ml. The Final concentration will be 38.7 mg/ml that will be stable for 24 hours in Room Temp. and 48 hours in Refrigeration",
    target_volume_ml: 23,
  },
  {
    trade_name: "Tienam",
    generic_name: "Imipenem/Cilastatin",
    arabic_name: "تينام",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 100,
    reconstitution_concentration_mg_ml: 5,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 4,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 15,
    max_dose_mg_kg_dose: 25,
    max_dose_mg_dose: 1000,
    max_dose_mg_day: 4000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Imipenem/Cilastatin) 500mg Powder Vial Should be reconstituted with 100ml of NS to produce concentration of 5mg/ml and will be stable for 4 hours in Room Temp and for 24 hours in Refrigeration. Withdraw the Calculated mls",
    target_volume_ml: 100,
  },
  {
    trade_name: "Tygacil",
    generic_name: "Tigecycline",
    arabic_name: "تيجاسيل",
    form: "Powder",
    container: "Vial",
    amount_mg: 50,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 5.3,
    reconstitution_concentration_mg_ml: 10,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 24,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 20,
    fd_concentration_mg_ml: 0.5,
    fdfr_each_ml_up_to: 10,
    fdfr_concentration_mg_ml: 1,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: 2,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 1,
    max_dose_mg_kg_dose: 3,
    max_dose_mg_dose: 50,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "",
    instructions_text:
      "(Tigecycline) 50mg Powder Vial Should be reconstituted with 5.3ml of NS or D5W to produce concentration of 10mg/ml and will be stable for 24 hours in Room Temp and for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 20 ml. The Final concentration will be 0.5 mg/ml that will be stable for 24 hours in Room Temp. and 48 hours in Refrigeration",
    target_volume_ml: 5,
  },
  {
    trade_name: "Unasyn 750",
    generic_name: "Ampicillin/Sulbactam",
    arabic_name: "يوناسين",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 4.7,
    reconstitution_concentration_mg_ml: 100,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 1,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 4,
    fd_concentration_mg_ml: 25,
    fdfr_each_ml_up_to: 3.5,
    fdfr_concentration_mg_ml: 28.57,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: 8,
    fd_stability_refrigeration_days: 2,
    infusion_time_min: 30,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 400,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 8000,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Ampicillin/Sulbactam) 500mg Powder Vial Should be reconstituted with 4.7ml of SWI to produce concentration of 100mg/ml and will be stable for 1 hours in Room Temp. Withdraw the Calculated mls and Further dilute with NS each ml up to 4 ml. The Final concentration will be 25 mg/ml that will be stable for 8 hours in Room Temp. and 48 hours in Refrigeration",
    target_volume_ml: 5,
  },
  {
    trade_name: "Vancomycin 1000",
    generic_name: "Vancomycin",
    arabic_name: "فانكوميسين",
    form: "Powder",
    container: "Vial",
    amount_mg: 1000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 20,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: 4,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 5,
    fdfr_each_ml_up_to: 5,
    fdfr_concentration_mg_ml: 10,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 48,
    fd_stability_refrigeration_days: 4,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 10,
    max_dose_mg_kg_dose: 25,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 3600,
    obese_patient_dosage_adjustment:
      "Give a loading dose of 20 mg/kg IV, followed by the usual empiric dose regimen",
    instructions_text:
      "(Vancomycin) 1000mg Powder Vial Should be reconstituted with 20ml of SWI to produce concentration of 50mg/ml and will be stable for 4 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 5 mg/ml that will be stable for 48 hours in Room Temp. and 4 days in Refrigeration",
    target_volume_ml: 20,
  },
  {
    trade_name: "Vancomycin 500",
    generic_name: "Vancomycin",
    arabic_name: "فانكوميسين",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: 4,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 5,
    fdfr_each_ml_up_to: 5,
    fdfr_concentration_mg_ml: 10,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 48,
    fd_stability_refrigeration_days: 4,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 10,
    max_dose_mg_kg_dose: 25,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 3600,
    obese_patient_dosage_adjustment:
      "Give a loading dose of 20 mg/kg IV, followed by the usual empiric dose regimen",
    instructions_text:
      "(Vancomycin) 500mg Powder Vial Should be reconstituted with 10ml of SWI to produce concentration of 50mg/ml and will be stable for 4 days in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 5 mg/ml that will be stable for 48 hours in Room Temp. and 4 days in Refrigeration",
    target_volume_ml: 10,
  },
  {
    trade_name: "Vfend",
    generic_name: "Voriconazole",
    arabic_name: "فيفيند",
    form: "Powder",
    container: "Vial",
    amount_mg: 200,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 19,
    reconstitution_concentration_mg_ml: 10,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: null,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 2,
    fd_concentration_mg_ml: 5,
    fdfr_each_ml_up_to: 2,
    fdfr_concentration_mg_ml: 5,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: 1,
    infusion_time_min: 180,
    is_photosensitive: 0,
    is_biohazard: 1,
    min_dose_mg_kg_dose: 3,
    max_dose_mg_kg_dose: 9,
    max_dose_mg_dose: 350,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "EBW",
    instructions_text:
      "(Voriconazole) 200mg Powder Vial Should be reconstituted with 19ml of SWI to produce concentration of 10mg/ml and will be stable for 24 hours in Refrigeration. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 2 ml. The Final concentration will be 5 mg/ml that will be stable for 24 hours in Refrigeration",
    target_volume_ml: 20,
  },
  {
    trade_name: "Zavicefta 2500",
    generic_name: "Ceftazidime/Avibactam",
    arabic_name: "زافيسيفتا",
    form: "Powder",
    container: "Vial",
    amount_mg: 2000,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 167,
    reconstitution_diluent_ns: 1,
    reconstitution_diluent_d5w: 1,
    reconstitution_diluent_swi: 0,
    reconstitution_stability_room_hours: 12,
    reconstitution_stability_refrigeration_days: 1,
    initial_dilution_volume_ml: 50,
    initial_dilution_concentration_mg_ml: 40,
    fd_each_ml_up_to: null,
    fd_concentration_mg_ml: null,
    fdfr_each_ml_up_to: null,
    fdfr_concentration_mg_ml: null,
    fd_diluent_ns: 0,
    fd_diluent_d5w: 0,
    fd_stability_room_hours: null,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 120,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 25,
    max_dose_mg_kg_dose: 50,
    max_dose_mg_dose: 2000,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "TBW up to adult max",
    instructions_text:
      "(Ceftazidime/Avibactam) 2000mg Powder Vial Should be reconstituted with 10ml and should be initially diluted with 50ml of NS or D5W to create concentration of 40 mg/ml and will be stable for 12 hours in Room Temp and for 24 hours in Refrigeration. Withdraw the Calculated mls",
    target_volume_ml: 50,
  },
  {
    trade_name: "Zovirax 250",
    generic_name: "Acyclovir",
    arabic_name: "زوفيراكس",
    form: "Powder",
    container: "Vial",
    amount_mg: 250,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 5,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 12,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 5,
    fdfr_each_ml_up_to: 7.2,
    fdfr_concentration_mg_ml: 6.94,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 5,
    max_dose_mg_kg_dose: 20,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "EBW",
    instructions_text:
      "(Acyclovir) 250mg Powder Vial Should be reconstituted with 5ml of SWI to produce concentration of 50mg/ml and will be stable for 12 hours in Room Temp. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 5 mg/ml that will be stable for 24 hours in Room Temp.",
    target_volume_ml: 5,
  },
  {
    trade_name: "Zovirax 500",
    generic_name: "Acyclovir",
    arabic_name: "زوفيراكس",
    form: "Powder",
    container: "Vial",
    amount_mg: 500,
    amount_volume_ml: null,
    concentration_mg_ml: null,
    reconstitution_volume_ml: 10,
    reconstitution_concentration_mg_ml: 50,
    reconstitution_diluent_ns: 0,
    reconstitution_diluent_d5w: 0,
    reconstitution_diluent_swi: 1,
    reconstitution_stability_room_hours: 12,
    reconstitution_stability_refrigeration_days: null,
    initial_dilution_volume_ml: null,
    initial_dilution_concentration_mg_ml: null,
    fd_each_ml_up_to: 10,
    fd_concentration_mg_ml: 5,
    fdfr_each_ml_up_to: 7.2,
    fdfr_concentration_mg_ml: 6.94,
    fd_diluent_ns: 1,
    fd_diluent_d5w: 1,
    fd_stability_room_hours: 24,
    fd_stability_refrigeration_days: null,
    infusion_time_min: 60,
    is_photosensitive: 0,
    is_biohazard: 0,
    min_dose_mg_kg_dose: 5,
    max_dose_mg_kg_dose: 20,
    max_dose_mg_dose: 0,
    max_dose_mg_day: 0,
    obese_patient_dosage_adjustment: "EBW",
    instructions_text:
      "(Acyclovir) 500mg Powder Vial Should be reconstituted with 10ml of SWI to produce concentration of 50mg/ml and will be stable for 12 hours in Room Temp. Withdraw the Calculated mls and Further dilute with NS/D5W each ml up to 10 ml. The Final concentration will be 5 mg/ml that will be stable for 24 hours in Room Temp.",
    target_volume_ml: 10,
  },
];
